import pandas as pd

print("Iniciando inyección de datos desde la memoria de la IA...")

# Datos extraídos directamente por visión artificial desde el PDF escaneado
datos_fifa = {
    "Algeria": "MASTIL,MANDI,ABADA,TOUGAI,BELAID,ZERROUKI,MAHREZ,AQUAR,GOUIRI,CHAIBI,HADJ MOUSSA,BENBOUALI,HADJAM,BOUDAOU,AIT-NOURI,BENBOT,BELGHALI,AMOURA,BENTALEB,BOULBINA,BENSEBAINI,MAZA,ZIDANE,TITRAQUI,GHEDJEMIS,CHERGUI",
    "Argentina": "MUSSO,SENESI,TAGLIAFICO,MONTIEL,PAREDES,MARTINEZ,DE PAUL,BARCO,ALVAREZ,MESSI,LO CELSO,RULLI,ROMERO,PALACIOS,GONZALEZ,ALMADA,SIMEONE,PAZ,OTAMENDI,MAC ALLISTER,LOPEZ,FERNANDEZ,MEDINA,MOLINA",
    "Australia": "RYAN,DEGENEK,CIRCATI,ITALIANO,BOS,GERIA,LECKIE,METCALFE,TOURE,HRUSTIC,MABIL,IZZO,ONEILL,DEVLIN,TREWIN,BEHICH,IRANKUNDA,BEACH,SOUTTAR,VOLPATO,BURGESS,IRVINE,VELUPILLAY,OKON-ENGSTLER,HERRINGTON,YENGI",
    "Austria": "SCHLAGER,AFFENGRUBER,DANSO,POSCH,SEIWALD,ARNAUTOVIC,ALABA,SABITZER,GRILLITSCH,GREGORITSCH,WIEGELE,PENTZ,KALAJDZIC,LIENHART,MWENE,CHUKWUEMEKA,SCHMID,LJUBICIC,LAIMER,WIMMER,PRASS,FRIEDL,WANNER,SVOBODA,SCHOEPF",
    "Belgium": "COURTOIS,DEBAST,THEATE,MECHELE,DE CUYPER,WITSEL,DE BRUYNE,TIELEMANS,LUKAKU,TROSSARD,DOKU,LAMMENS,PENDERS,LUKEBAKIO,MEUNIER,DE WINTER,DE KETELAERE,SEYS,MOREIRA,VANAKEN,CASTAGNE,SAELEMAEKERS,RASKIN,ONANA,NGOY,FERNANDEZ-PARDO",
    "Bosnia and Herzegovina": "VASILJ,MUJAKIC,HADZIKADUNIC,MUHAREMOVIC,KOLASINAC,TAHIROVIC,DEDIC,GIGOVIC,BAZDAR,DEMIROVIC,DZEKO,JURKAS,BASIC,SUNJIC,MEMIC,HADZIAHMETOVIC,BURNIC,KATIC,ALAJBEGOVIC,BAJRAKTAREVIC,RADELJIC,ZLOMISLIC,TABAKOVIC,MALIC,LUKIC,MAHMIC",
    "Brazil": "ALISSON,EDERSON,GABRIEL,MARQUINHOS,CASEMIRO,ALEX SANDRO,VINICIUS,BRUNO,CUNHA,NEYMAR,RAPHINHA,WEVERTON,DANILO,BREMER,PEREIRA,DOUGLAS,FABINHO,ENDRICK,PAQUETA,HENRIQUE,MARTINELLI,IBANEZ,THIAGO,RAYAN",
    "Cabo Verde": "VOZINHA,STOPIRA,BORGES,LOPES,COSTA,PINA,CABRAL,PAULO,BENCHIMOL,MONTEIRO,RODRIGUES,ROSA,DUARTE,SEMEDO,ARCANJO,LIVRAMENTO,MENDES,MOREIRA,DOS SANTOS,PIRES,VARELA",
    "Canada": "ST. CLAIR,JOHNSTON,JONES,DE FOUGEROLLES,WATERMAN,CHOINIERE,EUSTAQUIO,KONE,LARIN,DAVID,MILLAR,OLUWASEYI,CORNELIUS,SHAFFELBURG,BOMBITO,CREPEAU,BUCHANAN,GOODMAN,DAVIES,AHMED,OSORIO,LARYEA,SIGUR,SALIBA,NELSON",
    "Colombia": "OSPINA,MUNOZ,LUCUMI,ARIAS,CASTANO,RIOS,DIAZ,CARRASCAL,CORDOBA,RODRIGUEZ,VARGAS,MINA,PUERTA,PORTILLA,LERMA,MOJICA,DITTA,HERNANDEZ,QUINTERO,CAMPAZ,MACHADO,SANCHEZ,MONTERO,SUAREZ,GOMEZ",
    "Congo DR": "MPASI,WAN-BISSAKA,KAPUADI,TUANZEBE,BATUBINSIKA,MUKAU,MBUKU,MOUTOUSSAMY,CIPENGA,BONGONDA,KAKUTA,KAYEMBE,ELIA,SADIKI,TSHIBOLA,FAYULU,BAKAMBU,PICKEL,MAYELE,WISSA,EPOLO,MBEMBA,BANZA,KALULU,MASUAKU",
    "Ivory Coast": "FOFANA,DIOMANDE,KONAN,SERI,SINGO,KOSSOUNOU,KESSIE,BONNY,ADINGRA,WAHI,OPERI,DIAKITE,DIALLO,KONE,DOUE,SANGARE,PEPE,AGBADOU,NDICKA,GUESSAND,LAFONT,TOURE,GUIAGON,OULAI",
    "Croatia": "LIVAKOVIC,STANISIC,PONGRACIC,GVARDIOL,CALETA-CAR,SUTALO,MORO,KOVACIC,KRAMARIC,MODRIC,BUDIMIR,PANDUR,VLASIC,PERISIC,PASALIC,BATURINA,SUCIC,JAKIC,FRUK,MATANOVIC,VUSKOVIC,KOTARSKI,ERLIC,MUSA",
    "Curaçao": "ROOM,SAMBO,GAARI,VAN EIJMA,FLORANUS,ROEMERATOE,BACUNA,COMENENCIA,LOCADIA,ANTONISSE,HANSEN,NOSLIN,GORRE,MARTHA,MARGARITHA,KUWAS,OBISPO,KASTANEER,BRENET,CHONG,FELIDA,BAZOER,FONVILLE,BODAK,DOORNBUSCH",
    "Czechia": "KOVAR,ZIMA,HOLES,HRANAC,COUFAL,CHALOUPEK,KREJCI,DARIDA,HLOZEK,SCHICK,KUCHTA,CERV,CHYTIL,JURASEK,SULC,STANEK,PROVOD,SADILEK,CHORY,ZELENY,DOUDERA,SOUCEK,HORNICEK,SOJKA,SOCHUREK,VISINSKY",
    "Ecuador": "GALINDEZ,TORRES,HINCAPIE,ORDONEZ,ALCIVAR,PACHO,ESTUPINAN,VALENCIA,YEBOAH,PAEZ,RODRIGUEZ,RAMIREZ,MINDA,VITE,CAICEDO,PRECIADO,CASTILLO,PLATA,ANGULO,FRANCO,VALLE,AREVALO,POROZO,MEDINA",
    "Egypt": "ELSHENAWY,YASSER,HANY,ABDELMAGUID,RABIA,ABDELMONEIM,TREZEGUET,ASHOUR,ABDELKARIM,SALAH,ZICO,HASSAN,FATOUH,FATHY,HAFEZ,SOLIMAN,LASHIN,DONGA,ATTIA,ADEL,SABER,MARMOUSH,SHOUBIR,ALAA,ZIZO",
    "England": "PICKFORD,KONSA,OREILLY,RICE,STONES,GUEHI,SAKA,ANDERSON,KANE,BELLINGHAM,RASHFORD,CHALOBAH,HENDERSON,BURN,MAINOO,ROGERS,GORDON,WATKINS,MADUEKE,EZE,TONEY,TRAFFORD,JAMES,SPENCE,QUANSAH",
    "France": "SAMBA,GUSTO,DIGNE,UPAMECANO,KOUNDE,KONE,DEMBELE,TCHOUAMENI,THURAM,MBAPPE,OLISE,BARCOLA,KANTE,RABIOT,KONATE,MAIGNAN,SALIBA,ZAIRE-EMERY,HERNANDEZ,DOUE,MATETA,RISSER,CHERKI,AKLIOUCHE,LACROIX",
    "Germany": "NEUER,RUEDIGER,ANTON,TAH,PAVLOVIC,KIMMICH,HAVERTZ,GORETZKA,LEWELING,MUSIALA,WOLTEMADE,BAUMANN,GROSS,BEIER,SCHLOTTERBECK,STILLER,WIRTZ,BROWN,SANE,AMIRI,NUEBEL,RAUM,NMECHA,THIAW,QUEDRAOGO,UNDAV",
    "Ghana": "ZIGI,SEIDU,YIRENKYI,ADJETEY,PARTEY,MUMIN,FATAWU,SIBO,AYEW,THOMAS-ASANTE,SEMENYO,ANANG,BAAH,MENSAH,OWUSU,ASARE,RAHMAN,OPOKU,WILLIAMS,BOAKYE,OPPONG,SULEMANA,LUCKASSEN,NUAMAH,ADU,SENAYA",
    "Haiti": "PLACIDE,ARCUS,THERMONCY,ADE,DELCROIX,SAINTE,ETIENNE,EXPERIENCE,NAZON,BELLEGARDE,DEEDSON,PIERRE,LACROIX,METUSALA,PROVIDENCE,JOSEPH,JACQUES,ISIDOR,FORTUNE,PIERROT,CASIMIR,DUVERNE,DUVERGER,PAUGAIN,SIMON",
    "Iran": "BEIRANVAND,HARDANI,HAJISAFI,KHALILZADEH,MOHAMMADI,EZATOLAHI,JAHANBAKHSH,MOHEBBI,TAREMI,GHAYEDI,ALIPOUR,NIAZMAND,KANANI,GHODDOS,CHESHMI,TORABI,YOUSEFI,HOSSEINZADEH,NEMATI,MOGHANLOO,GHORBANI,HOSSEINI,REZAEIAN,DARGAHI,IRI,RAZAGHINIA",
    "Iraq": "TALIB,SULAKA,ALI,TAHSEEN,HASHIM,YOUNUS,AMYN,BAYESH,ALHAMADI,MOHANAD,QASEM,HASSAN,YOUSIF,IQBAL,MAKNAZI,ALAMMARI,JASIM,HUSSEIN,YAKOB,SHER,FARJI,BASIL,DOSKI,ISMAEL,SAADOON,PUTROS",
    "Japan": "SUZUKI,SUGAWARA,TANIGUCHI,ITAKURA,NAGATOMO,MACHINO,TANAKA,KUBO,GOTO,DOAN,MAEDA,OSAKO,NAKAMURA,ITO,KAMADA,WATANABE,UEDA,OGAWA,SEKO,TOMIYASU,HAYAKAWA,SANO,SHIOGAI",
    "Jordan": "ABULAILA,ABUHASHEESH,NASIB,ABUDAHAB,ALARAB,JAMOUS,ABUZRAIQ,ALRAWABDEH,ALLOLWAN,ALTAMARI,FAKHOURY,BANIATEYAH,ALMARDI,AYED,SADEH,ABUALNADI,OBAID,ABUGHOUSH,ALROSAN,ABUTAHA,ALRASHDAN,ALFAKHORI,HADDAD,AZAIZEH,ALDAOUD,BADAWI",
    "South Korea": "KIM,LEE,HWANG,SON,PAIK,CHO,SONG,PARK,BAE,OH,YANG,JO,SEOL,CASTROP,EOM,DONGGYEONG",
    "Mexico": "RANGEL,SANCHEZ,MONTES,ALVAREZ,VASQUEZ,LIRA,ROMO,FIDALGO,JIMENEZ,VEGA,GIMENEZ,ACEVEDO,OCHOA,GONZALEZ,REYES,QUINONES,PINEDA,VARGAS,MORA,CHAVEZ,HUERTA,MARTINEZ,GALLARDO,ALVARADO,GUTIERREZ",
    "Morocco": "BOUNOU,HAKIMI,MAZRAOUI,AMRABAT,SAADANE,BOUADDI,TALBI,OUNAHI,RAHIMI,DIAZ,SAIBARI,KAJOUI,QUAHDI,DIOP,MOURABET,YASSINE,SBAI,RIAD,BELAMMARI,KAABI,AMAIMOUNI,TAGNAOUTI,KHANNOUSS,AYNAOUI,HALHAL,SALAH",
    "Netherlands": "VERBRUGGEN,GEERTRUIDA,ROON,DIJK,AKE,HECKE,KLUIVERT,GRAVENBERCH,WEGHORST,DEPAY,GAKPO,WIEFFER,ROEFS,REIJNDERS,VEN,TIL,LANG,MALEN,BROBBEY,KOOPMEINERS,JONG,DUMFRIES,FLEKKEN,SUMMERVILLE,HATO,TIMBER",
    "New Zealand": "CROCOMBE,PAYNE,VRIES,BINDON,BOXALL,BELL,ROGERSON,STAMENIC,WOOD,SINGH,JUST,PAULSEN,CACACE,RUFER,PIJNAKER,SURMAN,BARBAROUSES,WAINE,OLD,MCCOWATT,RANDALL,WOUD,THOMAS,ELLIOT,BAYLISS,SMITH",
    "Norway": "NYLAND,THORSBY,AJER,OSTIGARD,WOLFE,BERG,SORLOTH,BERGE,HAALAND,ODEGAARD,LARSEN,TANGVIK,SELVIK,AURSNES,BJORKAN,PEDERSEN,HEGGEM,THORSTVEDT,AASGAARD,NUSA,SCHJELDERUP,BOBB,HAUGE,LANGAS,FALCHENER,RYERSON",
    "Panama": "MEJIA,BLACKMAN,CORDOBA,ESCOBAR,FARINA,MARTINEZ,RODRIGUEZ,CARRASQUILLA,DIAZ,BARCENAS,SAMUDIO,RAMOS,HARVEY,DAVIS,ANDRADE,FAJARDO,WATERMAN,QUINTERO,GODOY,YANIS,MOSQUERA,MURILLO,LONDONO,MILLER,GUTIERREZ",
    "Paraguay": "FERNANDEZ,VELAZQUEZ,ALDERETE,CACERES,BALBUENA,ALONSO,SOSA,GOMEZ,SANABRIA,ALMIRON,MAURICIO,GILL,CANALE,CUBAS,BOBADILLA,GAMARRA,ARCE,ENCISO,OJEDA,AVALOS,OLVEIRA,GALARZA,CABALLERO,PITTA,MAIDANA",
    "Portugal": "COSTA,SEMEDO,DIAS,ARAUJO,DALOT,NUNES,RONALDO,FERNANDES,RAMOS,SILVA,FELIX,SA,VEIGA,INACIO,NEVES,TRINCAO,LEAO,NETO,GUEDES,CANCELO,MENDES,CONCEICAO",
    "Qatar": "ABUNADA,MIGUEL,MENDES,LAYE,GABER,HATEM,ALAAELDIN,EDMILSON,MUNTARI,ALHAYDOS,AFIF,BOUDIAF,ALOUI,AHMED,ABDURISAG,KHOUKHI,ALGANEHI,ALBRAKE,ALI,FATHY,ZAKARIA,BARSHAM,MADIBO,MOHAMMED,ALHUSSEIN,MANAI",
    "Saudi Arabia": "ALAQIDI,MAJRASHI,LAJAMI,ALAMRI,ALTAMBAKTI,ALDAWSARI,ALJUWAYR,YAHYA,ALBRIKAN,ALSHEHRI,ABDULHAMID,WASHL,KADISH,ALKHAIBARI,ALJOHANI,ALGHANNAM,ALHAJJI,ALHAMDDAN,MANDASH,ALOWAIS,ALKASSAR,KANNO,ALHARBI,THIKRI,ALSHAMAT",
    "Scotland": "GUNN,HICKEY,ROBERTSON,MCTOMINAY,HANLEY,TIERNEY,MCGINN,FLETCHER,DYKES,ADAMS,CHRISTIE,KELLY,HENDRY,STEWART,SOUTTAR,HYAM,DOAK,HIRST,FERGUSON,SHANKLAND,GORDON,PATTERSON,MCLEAN,RALSTON,CURTIS,MCKENNA",
    "Senegal": "DIOUF,SARR,KOULIBALY,SECK,GUEYE,CISS,DIAO,CAMARA,DIENG,MANE,JACKSON,NDIAYE,JAKOBS,DIATTA,MENDY,NIAKHATE,MBAYE,DIARRA",
    "South Africa": "WILLIAMS,MATULUDI,NDAMANE,MOKOENA,MBATHA,MODIBA,APPOLLIS,MOREMI,FOSTER,MOFOKENG,ZWANE,MASEKO,SITHOLE,MBOKAZI,RAYNERS,CHAINE,MAKGOPA,KABINI,SIBISI,MUDAU,OKON,GOSS,ADAMS,MAKHANYA,SEBELEBELE,CROSS",
    "Spain": "RAYA,PUBILL,GRIMALDO,GARCIA,LLORENTE,MERINO,TORRES,RUIZ,GAVI,OLMO,PINO,PORRO,LAPORTE,BAENA,RODRI,WILLIAMS,ZUBIMENDI,YAMAL,PEDRI,OYARZABAL,CUBARSI,SIMON,CUCURELLA,MUNOZ,IGLESIAS",
    "Sweden": "ZETTERSTROM,LAGERBIELKE,LINDELOF,HIEN,GUDMUNDSSON,JOHANSSON,BERGVALL,SVENSSON,ISAK,NYGREN,ELANGA,SEMA,EKDAL,STARFELT,KARLSTROM,GYOKERES,AYARI,SVANBERG,SMITH,BERNHARDSSON,ZENELI,NORDFELDT,STROUD,NILSSON,ALI",
    "Switzerland": "KOBEL,MUHEIM,WIDMER,ELVEDI,AKANJI,ZAKARIA,EMBOLO,FREULER,MANZAMBI,XHAKA,NDOYE,MVOGO,RODRIGUEZ,JASHARI,SOW,FASSNACHT,VARGAS,COEMERT,OKAFOR,AEBISCHER,KELLER,RIEDER,AMDOUNI,AMENDA,JAQUEZ,ITTEN",
    "Tunisia": "CHAMAKH,ABDI,TALBI,REKIK,AROUS,BRONN,ACHOURI,SAAD,MASTOURI,MEJBRI,GHARBI,QUANES,KHEDIRA,AYARI,MAHMOUD,DAHMEN,SKHIRI,ELLOUMI,CHAOUAT,VALERY,HMIDA,HESSEN,NEFFATI,CHIKHAOUI,SLIMANE,TOUNEKTI",
    "Türkiye": "GUNOK,CELIK,DEMIRAL,SOYUNCU,OZCAN,KOKCU,AKTURKOGLU,GULER,GUL,CALHANOGLU,YILDIZ,BAYINDIR,ELMALI,BARDAKCI,KABAK,YUKSEK,KAHVECI,MULDUR,AKGUN,KADIOGLU,YILMAZ,AYHAN,CAKIR,AYDIN,AKAYDIN,UZUN",
    "Uruguay": "ROCHET,GIMENEZ,CACERES,ARAUJO,UGARTE,BENTANCUR,CRUZ,VALVERDE,NUNEZ,ARRASCAETA,PELLISTRI,MELE,VARELA,CANOBBIO,MARTINEZ,OLIVERA,VINA,RODRIGUEZ,AGUIRRE,VINAS,PIQUEREZ,MUSLERA,BUENO,SANABRIA,ZALAZAR",
    "USA": "TURNER,DEST,RICHARDS,ADAMS,ROBINSON,TRUSTY,REYNA,MCKENNIE,PEPI,PULISIC,AARONSON,REAM,BERHALTER,ROLDAN,FREEMAN,TILLMAN,ARFSTEN,WRIGHT,BALOGUN,WEAH,MCKENZIE,SCALLY,FREESE,BRADY,ZENDEJAS",
    "Uzbekistan": "YUSUPOV,KHUSANOV,ALIJONOV,SAYFIEV,ASHURMATOV,MOZGOVOY,SHUKUROV,ISKANDEROV,XAMROBEKOV,JIYANOV,URUNOV,NEMATOV,NASRULLAEV,SHOMURODOV,ESHMURODOV,ERGASHEV,KHAMDAMOV,ABDULLAEV,GANIEV,AMONOV,SERGEEV,FAYZULLAEV,ESANOV,KARIMOV,ULMASALIYEV,UROZOV"
}

filas = []
for equipo, jugadores in datos_fifa.items():
    nombres = jugadores.split(',')
    for nombre in nombres:
        filas.append({'Equipo': equipo, 'Jugador_Oficial': nombre.strip()})

df = pd.DataFrame(filas)
df.to_csv("convocados_oficiales.csv", index=False, encoding='utf-8')
print(f"¡Éxito! Se ha creado la base de datos oficial con {len(df)} jugadores blindados.")